### ISSUE TITLE
Not able to replicate results of paper

### ISSUE THREAD

**Issue by suxnju** [JetBrains-Research/code2seq#73]
Hi, thanks for sharing your code! 
After running the code for 12 epochs (early stopping) on the java-small dataset, the F1 score on testing data is only 26.6% (the original paper shows 43.2%).
Do you have any ideas on this? Thanks!

**Comment by SpirinEgor** [comment]
Hi!
I apologize for not answering for a long time :( 

Currently, this code under "work in progress" because we can't reproduce results too. It seems that there is a problem with the decoder, I implement it like in the paper, but it seems that the original version has differents because of `AttentionWrapper`. For more details see this [issue](https://github.com/tech-srl/code2seq/issues/63).

I looking forward to fixing it and reproduce the original paper but I have some side projects, so it would take some time. If you have some ideas I will be glad to hear them.
